### PR TITLE
Update build.gradle to support React 0.69.0 & Gradle 7

### PR DESCRIPTION
**Pull request by cluth17**
compile has been removed. replacing with implementation.

### CODE REVIEW

**Comment by cluth17** [comment]
Can this get merged? I've tested in my local and this is the last thing needed to support gradle 7.

**Comment by harpreetCD** [comment]
Hi, I have tried your patch. but it is giving ```Plugin with id 'maven' not found```. I guess moving to implementation is also required but maven plugin is also not supported. Please verify

**Comment by cluth17** [comment]
This PR in combination with this PR should fix all the Gradle 7 issues. The other PR has already been merged but not deployed to npm. https://github.com/gusparis/react-native-month-year-picker/pull/116

**Comment by harpreetCD** [comment]
not deployed because the publish script is removed in that PR? 🙄

**Comment by nimeshkavinda** [comment]
Any idea when this will be merged? need this fix asap

**Comment by nimeshkavinda** [comment]
> Hi, I have tried your patch. but it is giving `Plugin with id 'maven' not found`. I guess moving to implementation is also required but maven plugin is also not supported. Please verify

This should be renamed to "maven-publish"

**Comment by gusparis** [comment]
Hey! sorry I've been having some personal issues. I will be getting everything up-to-date

**Pull request closed without merging**
